apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "product-traceability-foss-frontend.fullname" . }}
  labels:
    {{- include "product-traceability-foss-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "product-traceability-foss-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "product-traceability-foss-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "product-traceability-foss-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CATENAX_PORTAL_API_URL
              value: "{{ .Values.image.CATENAX_PORTAL_API_URL }}"
            - name: CATENAX_PORTAL_KEYCLOAK_URL
              value: "{{ .Values.image.CATENAX_PORTAL_KEYCLOAK_URL }}"
            - name: CATENAX_PORTAL_CLIENT_ID
              value: "{{ .Values.image.CATENAX_PORTAL_CLIENT_ID }}"
            - name: CATENAX_PORTAL_DEFAULT_REALM
              value: "{{ .Values.image.CATENAX_PORTAL_DEFAULT_REALM }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
