environment: "dev"

image:
  repository: ftcpro.azurecr.io/frontend/traceability
  pullPolicy: Always
  tag: "latest"
  CATENAX_PORTAL_API_URL: 'https://traceability.dev.demo.ftcpro.co/api'
  CATENAX_PORTAL_KEYCLOAK_URL: 'https://centralidp.dev.demo.ftcpro.co/auth'
  CATENAX_PORTAL_CLIENT_ID: 'Cl10-CX-Part'
  CATENAX_PORTAL_DEFAULT_REALM: 'CX-Central'


autoscaling:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: "traceability-portal.dev.demo.ftcpro.co"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "traceability-portal.dev.demo.ftcpro.co"
      # Default secret for certificate creation already provided to your namespace
      secretName: tls-secret


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 100Mi


